BOARD_TAG = mega2560
ARDUINO_PORT = /dev/ttyS0
USER_LIB_PATH = /home/pi/pyduino/arduino/libraries/
ARDUINO_LIBS = SDI12 hydrogeolog SparkFun_MS5803_I2C Sensirion OneWire dht DallasTemperature Adafruit_SI1145_Library Wire
include /usr/share/arduino/Arduino.mk
